# Generated by Django 5.2.8 on 2025-11-09 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Укажите ФИО сотрудника",
                        max_length=500,
                        verbose_name="ФИО сотрудника",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        help_text="Укажите должность сотрудника",
                        max_length=100,
                        verbose_name="Должность сотрудника",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Укажите название задачи",
                        max_length=100,
                        verbose_name="Название задачи",
                    ),
                ),
                ("deadline", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("at_work", "В работе"),
                            ("completed", "Выполнена"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "parental_task",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите родительскую задачу",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subtasks",
                        to="tasks.task",
                        verbose_name="Родительская задача",
                    ),
                ),
                (
                    "performer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите исполнителя",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performer",
                        to="tasks.employee",
                        verbose_name="Исполнитель",
                    ),
                ),
            ],
        ),
    ]
