# Generated by Django 5.2.8 on 2025-11-09 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={
                "ordering": ("full_name",),
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
            },
        ),
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ("-deadline",),
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
            },
        ),
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(help_text="Укажите срок", verbose_name="Срок"),
        ),
        migrations.AlterField(
            model_name="task",
            name="performer",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите исполнителя",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="tasks.employee",
                verbose_name="Исполнитель",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Новая"),
                    ("at_work", "В работе"),
                    ("completed", "Выполнена"),
                ],
                default="new",
                help_text="Укажите статус",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
