# Generated by Django 5.2.8 on 2025-11-11 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_employee_options_alter_task_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Новая"),
                    ("at_work", "В работе"),
                    ("completed", "Выполнена"),
                    ("cancelled", "Отменена"),
                ],
                default="new",
                help_text="Укажите статус",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
